### PR TITLE
Support for checkbox inputs

### PR DESCRIPTION
**Pull request by jrutila**
Checks the value of an input[type="checkbox"] from checked value instead of value.

Also added more BootstrapVue components (as needed examples) to example four.

### CODE REVIEW

**Comment by jarvelov** [comment]
Hi!

Thanks for the contribution, I'll review this as soon as possible and get back to you!

**Comment by jarvelov** [comment]
Hello again,

I've tested out your code and there are some things I want to adjust before this can be merged. I noticed that the code I've written to handle the `checked` attributes needs to be updated as it checks the component's name (which would be `input`) rather than the presence of a `checked` in `attrs` and/or `domProps`.

The changes in the `vfjsFieldHelperEventHandler` function cannot be merged however as they only make sense when using a checkbox to produce a true/false value, however that would fail for any checkbox where the value should be the one from `event.target.value`, which means this field would get the wrong value:

```
{
  component: 'input',
  model: 'fruits',
  valueProp: 'value', // This is the default value, it's just added here to be explicit
  fieldOptions: {
    attrs: {
      id: 'fruits-orange',
      name: 'fruits',
      type: 'checkbox',
    },
    domProps: {
      value: 'orange',
    },
    class: ['form-check-input'],
    on: ['change'],
  },
},
```

Also, is there a reason you are not using the `options.castToType` setting? You can see it in use in [Example 6](https://4rykx7jj19.codesandbox.io/).

Why I'm asking is because I'm guessing that you're setting `valueProp: 'checked'` to get the value in the `model` as a `boolean`? If that's what you're after you could just set `castToType` and the value of all models will be cast as the type that is defined in the JSON Schema. See the `radio` buttons in the linked example to see what I mean.

Either way, thank you very much for the contribution! I'll merge the applicable changes when I've had time to rewrite the code I talked about at the start of this comment. I'll ping you when they're merged!

**Comment by jrutila** [comment]
Thank you for reviewing it so quickly. I have to admit I had little trouble with the architecture of the library and was a little worried if I am doing it right. This PR rose from the need of adding a single checkbox that would produce true/false values and I tried many things but as the examples were missing checkbox case (I saw the radiobutton case) I wasn't sure.

I will try the castToSchemaType option, again. But I would still argue that the checkbox (without castToSchemaType and domProps:value) should work as is shown in example 8 in the PR. So just boolean property in schema and the basic input[type='checkbox'] in uiSchema.

**Comment by jarvelov** [comment]
I've put some thought into what you're arguing for and I think automatically setting `true`/`false` is too much "magic" and special consideration for one use case. I think that behavior would be suitable for a custom component as it diverges from how native HTML forms work.

If one would submit a normal HTML form which would POST the values to a server and in the form there is a native `input[checkbox]` element without a value attribute, then in the form data the value would be `on`. Check the POST request in the developer tools in this example: http://jsfiddle.net/ywj2m0ut/

To be true to the default behavior that's what should be implemented when a checkbox doesn't have a value set, but I don't foresee any demand for that.

However, an implementation that would be in the vein of how VFJS acts today would be to give the `input` a value, either `true` or `false` and let the field's model key be unset when the checkbox is unchecked. See the GIF below for an example of how it works and how the model is updated.

toggle-checkbox

The field's uiSchema from the GIF looks like this:

```js
{
  component: 'input',
  model: 'likesBread',
  fieldOptions: {
    attrs: {
      id: 'likesBread',
      type: 'checkbox',
    },
    domProps: {
      value: true,
    },
    class: ['form-check-input'],
    on: ['change'],
  },
},
```

The behavior in the GIF isn't available today but I will introduce it in the next version.

**Comment by jarvelov** [comment]
In `v2.7.0` I've added the  [eventProp](https://jarvelov.gitbook.io/vue-form-json-schema/api/vue-form-json-schema/ui-schema/field/event-prop) setting which makes it easier to use checkboxes if you only want boolean values. As of this added feature I will close this PR as the outcome is the same. Thank you for your contribution

```js
{
      component: 'input',
      model: 'isChecked',
      eventProp: 'checked', // This setting will make VFJS take the value from 'event.target.checked' and emit as the field's value
      valueProp: 'checked',
      fieldOptions: {
        type: "checkbox",
        on: ['change']
      }
    }
}
```

Note that this only lets you easily handle boolean values, if you want other values like strings of `Yes` / `No` then you have to use a custom component (recommended), or have the UI schema be a `computed` property so you can do something like this:

```js
{
      component: 'input',
      model: 'isChecked',
      fieldOptions: {
        type: "checkbox",
        on: ['change'],
        domProps: {
          checked: this.model.isChecked === 'Yes' ? 'checked' : '',
          value: this.model.isChecked === 'Yes' ? 'No' : 'Yes'
        }
      }
    }
}
```

[Full demo of the code above](https://codesandbox.io/s/example-1-hy7jp?file=/src/components/example-one.vue)

Note that I do not recommend this as it will negatively impact performance, since the `uiSchema` will be regenerated unnecessarily with every change to `this.model.isChecked`, which causes unnecessary re-renders. Try to use a custom component instead.

**Pull request closed without merging**
